const API='https://nqzffgrwsbuxwrfbunbs.supabase.co/functions/v1/canvas-api';
const OFF=500000000, MIN=-OFF, MAX=OFF, CHUNK=512;
const $=id=>document.getElementById(id);
const canvas=$('world');
const ctx=canvas.getContext('2d',{alpha:false});
const memory={};
function get(k,d){try{const v=localStorage.getItem(k);return v===null?d:v}catch{return memory[k]??d}}
function set(k,v){try{localStorage.setItem(k,String(v))}catch{memory[k]=String(v)}}
function num(v,d=0){const n=Number(v);return Number.isFinite(n)?n:d}
function clamp(v,a,b){return Math.max(a,Math.min(b,num(v,(a+b)/2)))}
function randomCoord(){return Math.floor(MIN+Math.random()*(MAX-MIN))}
function readCoord(k){const n=Number(get(k,''));return Number.isFinite(n)&&n>=MIN&&n<=MAX?n:randomCoord()}
function makeId(){return globalThis.crypto?.randomUUID?.()||String(Date.now())+'-'+Math.random()}
function toStorePoint(p){return{x:Math.round(clamp(p.x,MIN,MAX)+OFF),y:Math.round(clamp(p.y,MIN,MAX)+OFF)}}
function fromStorePoint(p){return{x:num(p.x,OFF)-OFF,y:num(p.y,OFF)-OFF}}
function toStoreStroke(st){return{sessionId:S.session,userName:st.user_name,color:st.color,width:st.width,points:st.points.map(toStorePoint)}}
function fromStoreStroke(st){if(!st||!Array.isArray(st.points))return null;return{...st,points:st.points.map(fromStorePoint)}}
const S={x:readCoord('uc.x'),y:readCoord('uc.y'),z:clamp(Number(get('uc.zoom','1'))||1,.05,12),mode:get('uc.mode','draw'),session:get('uc.session',makeId()),dpr:1,strokes:new Map(),active:[],down:false,pan:false,pid:null,last:null,seq:0,pending:new Map(),loading:false,lastKey:''};
set('uc.session',S.session);
function status(t,bad=false){$('status').textContent=t;$('status').className=bad?'bad':'ok'}
function counters(){$('count').textContent=S.strokes.size;$('pending').textContent=S.pending.size}
function saveCamera(){set('uc.x',Math.round(S.x));set('uc.y',Math.round(S.y));set('uc.zoom',S.z)}
function resize(){S.dpr=Math.max(1,Math.min(2,devicePixelRatio||1));canvas.width=Math.floor(innerWidth*S.dpr);canvas.height=Math.floor(innerHeight*S.dpr);draw()}
function s2w(px,py){return{x:Math.round(S.x+(px-innerWidth/2)/S.z),y:Math.round(S.y+(py-innerHeight/2)/S.z)}}
function w2s(x,y){return{x:(x-S.x)*S.z+innerWidth/2,y:(y-S.y)*S.z+innerHeight/2}}
function viewParams(){const a=s2w(0,0),b=s2w(innerWidth,innerHeight);const minX=clamp(Math.min(a.x,b.x),MIN,MAX)+OFF,minY=clamp(Math.min(a.y,b.y),MIN,MAX)+OFF,maxX=clamp(Math.max(a.x,b.x),MIN,MAX)+OFF,maxY=clamp(Math.max(a.y,b.y),MIN,MAX)+OFF;return{minCx:Math.floor(minX/CHUNK),minCy:Math.floor(minY/CHUNK),maxCx:Math.floor(maxX/CHUNK),maxCy:Math.floor(maxY/CHUNK)}}
function visible(st){if(st?.local)return true;if(!st||!Array.isArray(st.points))return false;const m=900/S.z;const l=S.x-innerWidth/(2*S.z)-m,r=S.x+innerWidth/(2*S.z)+m,t=S.y-innerHeight/(2*S.z)-m,b=S.y+innerHeight/(2*S.z)+m;return st.points.some(p=>p.x>=l&&p.x<=r&&p.y>=t&&p.y<=b)}
function drawGrid(){const step=CHUNK*S.z;if(step<28)return;const a=s2w(0,0),b=s2w(innerWidth,innerHeight);const sx=Math.floor(a.x/CHUNK)*CHUNK,sy=Math.floor(a.y/CHUNK)*CHUNK;ctx.save();ctx.scale(S.dpr,S.dpr);ctx.strokeStyle='rgba(17,24,39,.06)';ctx.lineWidth=1;for(let x=sx;x<=b.x;x+=CHUNK){const p=w2s(x,0).x;ctx.beginPath();ctx.moveTo(p,0);ctx.lineTo(p,innerHeight);ctx.stroke()}for(let y=sy;y<=b.y;y+=CHUNK){const p=w2s(0,y).y;ctx.beginPath();ctx.moveTo(0,p);ctx.lineTo(innerWidth,p);ctx.stroke()}ctx.restore()}
function drawStroke(st,preview=false){const pts=Array.isArray(st)?st:st.points;if(!pts?.length)return;ctx.save();ctx.scale(S.dpr,S.dpr);ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle=preview?$('color').value:(st.color||'#111111');ctx.lineWidth=Math.max(3,Number(preview?$('width').value:st.width||10)*S.z);let p=w2s(pts[0].x,pts[0].y);ctx.beginPath();ctx.moveTo(p.x,p.y);for(let i=1;i<pts.length;i++){p=w2s(pts[i].x,pts[i].y);ctx.lineTo(p.x,p.y)}ctx.stroke();ctx.restore()}
function draw(){S.x=clamp(S.x,MIN,MAX);S.y=clamp(S.y,MIN,MAX);S.z=clamp(S.z,.05,12);ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);drawGrid();S.strokes.forEach(st=>{if(visible(st))drawStroke(st)});if(S.active.length)drawStroke(S.active,true);$('pos').textContent=Math.round(S.x).toLocaleString()+','+Math.round(S.y).toLocaleString();$('zoom').textContent=S.z.toFixed(2)+'x';$('chunk').textContent=Math.floor(S.x/CHUNK)+','+Math.floor(S.y/CHUNK);saveCamera()}
function simplify(pts){const out=[];let last=null;const d=Math.max(1,2/S.z);for(const p of pts){if(!last||Math.hypot(p.x-last.x,p.y-last.y)>=d){out.push({x:clamp(p.x,MIN,MAX),y:clamp(p.y,MIN,MAX)});last=p}}if(out.length===1)out.push({x:clamp(out[0].x+1,MIN,MAX),y:clamp(out[0].y+1,MIN,MAX)});return out.slice(0,1024)}
function makeStroke(pts){const p=simplify(pts);if(p.length<2)return null;return{id:'local-'+(++S.seq),local:true,user_name:($('name').value||'anonymous').slice(0,32),color:$('color').value,width:Number($('width').value)||10,points:p,tries:0}}
async function saveStroke(st){S.pending.set(st.id,st);counters();try{const res=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(toStoreStroke(st))});if(!res.ok)throw new Error(await res.text());const json=await res.json();const saved=fromStoreStroke(json.stroke);S.strokes.delete(st.id);S.pending.delete(st.id);if(saved)S.strokes.set(saved.id,saved);status('saved');counters();draw();load(true)}catch(e){console.error(e);st.tries=(st.tries||0)+1;status('retry '+st.tries,true);setTimeout(()=>{if(S.pending.has(st.id))saveStroke(st)},Math.min(15000,800*Math.pow(1.5,st.tries)));counters()}}
async function load(force=false){if(S.loading)return;const v=viewParams(),key=Object.values(v).join(',');if(!force&&key===S.lastKey)return;S.loading=true;S.lastKey=key;const cam={x:S.x,y:S.y,z:S.z};try{const res=await fetch(API+'?'+new URLSearchParams(v)+'&t='+Date.now(),{cache:'no-store'});if(!res.ok)throw new Error(await res.text());const json=await res.json();for(const raw of json.strokes||[]){const st=fromStoreStroke(raw);if(st&&visible(st))S.strokes.set(st.id,st)}S.x=cam.x;S.y=cam.y;S.z=cam.z;status('sync');counters();draw()}catch(e){console.error(e);status('sync error',true)}finally{S.loading=false}}
function setMode(m){S.mode=m;set('uc.mode',m);$('drawBtn').classList.toggle('active',m==='draw');$('moveBtn').classList.toggle('active',m==='move');status(m)}
function start(e){e.preventDefault();S.pid=e.pointerId;try{canvas.setPointerCapture(e.pointerId)}catch{}S.last={x:e.clientX,y:e.clientY};S.pan=S.mode==='move'||e.shiftKey||e.altKey;S.down=!S.pan;if(S.down){S.active=[s2w(e.clientX,e.clientY)];draw()}}
function move(e){if(S.pid!==null&&e.pointerId!==S.pid)return;if(!S.last)return;e.preventDefault();if(S.pan){S.x-=num((e.clientX-S.last.x)/S.z,0);S.y-=num((e.clientY-S.last.y)/S.z,0);S.last={x:e.clientX,y:e.clientY};draw();return}if(S.down){S.active.push(s2w(e.clientX,e.clientY));draw()}}
function end(e){if(S.pid!==null&&e.pointerId!==S.pid)return;e.preventDefault();if(S.down){const st=makeStroke(S.active);S.active=[];if(st){S.strokes.set(st.id,st);counters();status('visible');draw();saveStroke(st)}}S.down=false;S.pan=false;S.pid=null;S.last=null;S.active=[];draw();load(true)}
canvas.addEventListener('pointerdown',start,{passive:false});canvas.addEventListener('pointermove',move,{passive:false});canvas.addEventListener('pointerup',end,{passive:false});canvas.addEventListener('pointercancel',end,{passive:false});
canvas.addEventListener('wheel',e=>{e.preventDefault();const before=s2w(e.clientX,e.clientY);S.z=clamp(S.z*(e.deltaY<0?1.12:.89),.05,12);const after=s2w(e.clientX,e.clientY);S.x+=before.x-after.x;S.y+=before.y-after.y;draw();load(false)},{passive:false});
$('drawBtn').onclick=()=>setMode('draw');$('moveBtn').onclick=()=>setMode('move');$('spawn').onclick=()=>{S.x=randomCoord();S.y=randomCoord();S.strokes.clear();S.lastKey='';counters();draw();load(true)};$('reload').onclick=()=>{S.lastKey='';load(true)};$('copy').onclick=()=>{navigator.clipboard?.writeText(Math.round(S.x)+','+Math.round(S.y));status('copied')};$('goto').onclick=()=>{const x=Number($('goX').value),y=Number($('goY').value);if(Number.isFinite(x)&&Number.isFinite(y)){S.x=clamp(x,MIN,MAX);S.y=clamp(y,MIN,MAX);S.strokes.clear();S.lastKey='';draw();load(true)}};
window.addEventListener('resize',resize);window.addEventListener('orientationchange',()=>setTimeout(resize,250));window.addEventListener('keydown',e=>{const sp=340/S.z;if(e.key==='ArrowUp')S.y-=sp;if(e.key==='ArrowDown')S.y+=sp;if(e.key==='ArrowLeft')S.x-=sp;if(e.key==='ArrowRight')S.x+=sp;if(e.key.toLowerCase()==='d')setMode('draw');if(e.key.toLowerCase()==='m')setMode('move');draw();load(false)});
setMode(S.mode==='move'?'move':'draw');resize();status('ready');load(true);setInterval(()=>load(true),900);
