create table if not exists public.strokes (
  id bigint generated by default as identity primary key,
  session_id uuid not null,
  user_name text not null default 'anonymous',
  color text not null default '#111111',
  width smallint not null default 4,
  points jsonb not null,
  min_x bigint not null,
  min_y bigint not null,
  max_x bigint not null,
  max_y bigint not null,
  min_chunk_x integer not null,
  min_chunk_y integer not null,
  max_chunk_x integer not null,
  max_chunk_y integer not null,
  created_at timestamptz not null default now()
);

create index if not exists strokes_chunk_bounds_idx on public.strokes
  (min_chunk_x, max_chunk_x, min_chunk_y, max_chunk_y, created_at desc);

create index if not exists strokes_created_at_idx on public.strokes (created_at desc);

create or replace view public.canvas_stats as
select
  count(*)::bigint as stroke_count,
  min(created_at) as first_stroke_at,
  max(created_at) as latest_stroke_at
from public.strokes;
